### ISSUE TITLE
Customising behaviour with action inputs

### ISSUE THREAD

**Issue by vstirbu** [CompliancePal/modelcard-action#21]
## Motivation

The behaviour of the action can be modified by the user to match the needs/conventions of its own ML project.

For example, the user can extend the default validation rules by adding their own rules in the repository where the action runs (#14 ), or they can disable the default rule set (#20).

## Solution

The modelcard default behaviour should be customisable by overriding the default values via the [inputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) defined in the `action.yml`:

```yaml
name: 'modelcard-action'
description: 'Check that the project has an appropriate model card'
inputs:
  # an example parameter
  parameter:
    description: 'Parameter description'
    required: false
    default: '1'
runs:
  using: 'docker'
  image: 'Dockerfile'
```

## Current parameters

input | default | required 
--- | --- | --- 
customRules | `.modelcard/rules` | false
disableDefaultRules | false | false
