### ISSUE TITLE
Template validation function for Markdown formatted strings

### ISSUE THREAD

**Issue by vstirbu** [CompliancePal/modelcard-action#44]
Markdown descriptions provide a better way for capturing longer text than simple strings.

```yaml
model_details:
  description: |
    ## First section

    some text

    ## Second section

    more text
```

The validation function ensures that the markdown formatted property follows the required format described by the template:

```yaml
valid-markdown-description:
  given: '$.model_details.description',
  then:
    function: markdownTemplate,
    functionOptions:
      template: |
        ## First section

        ## Second section
```
